"""add_stripe_fields

Revision ID: 0a44f84abfa2
Revises: 00b0201ad918
Create Date: 2026-07-15 10:35:52.666540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a44f84abfa2'
down_revision: Union[str, None] = '00b0201ad918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.create_index('ix_api_keys_key_hash', 'api_keys', ['key_hash'], unique=False)
    op.add_column('organizations', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('stripe_subscription_status', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organizations', sa.Column('current_plan', sa.String(), nullable=True))
    op.create_index(op.f('ix_organizations_stripe_customer_id'), 'organizations', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_organizations_stripe_subscription_id'), 'organizations', ['stripe_subscription_id'], unique=False)
    op.create_index('idx_queued_runs_campaign_state_optimized', 'queued_runs', ['campaign_id', 'state'], unique=False, postgresql_where=sa.text("state = 'queued'"))
    op.drop_column('workflow_definitions', 'call_disposition_codes')
    
    # Backfill trial_ends_at for existing organizations
    op.execute("UPDATE organizations SET trial_ends_at = CURRENT_TIMESTAMP + INTERVAL '14 days'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_definitions', sa.Column('call_disposition_codes', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False))
    op.drop_index('idx_queued_runs_campaign_state_optimized', table_name='queued_runs', postgresql_where=sa.text("state = 'queued'"))
    op.drop_index(op.f('ix_organizations_stripe_subscription_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_stripe_customer_id'), table_name='organizations')
    op.drop_column('organizations', 'current_plan')
    op.drop_column('organizations', 'trial_ends_at')
    op.drop_column('organizations', 'stripe_subscription_status')
    op.drop_column('organizations', 'stripe_subscription_id')
    op.drop_column('organizations', 'stripe_customer_id')
    op.drop_index('ix_api_keys_key_hash', table_name='api_keys')
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    # ### end Alembic commands ###
